### Create Variables

In [ ]:
import tensorflow as tf 

weights = tf.Variable(tf.random_normal([784, 200], stddev=0.35), name='weights')
biases = tf.Variable(tf.zeros([200]), name='biases')

# variable initialize
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)

### Initialize variable with other variable

In [ ]:
weights = tf.Variable(tf.random_normal([784, 200], stddev=0.35), name='weights')
w2 = tf.Variable(weights.initialized_value(), name='w2')
w_twice = tf.Variable(weights.initialized_value() * 0.2, name='w_twice')


### Variable's Save and Load

In [ ]:
# save variable

v1 = tf.Variable(tf.constant([1, 2, 3, 4]), name='v1')
v2 = tf.Variable(tf.constant([5, 6, 7, 8]), name='v2')

init_op = tf.global_variables_initializer()
saver = tf.train.Saver()

with tf.Session() as sess:
    sess.run(init_op)
    
    # do some work...
    save_path = saver.save(sess, "/tmp/model.ckpt")
    print("model saved in file:", save_path)


In [ ]:
v1 = tf.Variable(tf.random_normal([3, 5], stddev=0.01), name='v1')
v2 = tf.Variable(tf.random_normal([2, 4], stddev=0.01), name='v2')

saver = tf.train.Saver()

with tf.Session() as sess:
    saver.restore(sess, "/tmp/model.ckpt")
    print('model restored')

In [3]:
import tensorflow as tf 

a = tf.add(3, 5)

with tf.Session() as sess:
    print(sess.run(a))

8


In [4]:
import tensorflow as tf 

x = 2
y = 3
op1 = tf.add(x, y)
op2 = tf.multiply(x, y)
op3 = tf.pow(op2, op1)

with tf.Session() as sess:
    op3 = sess.run(op3)
    print(op3)

7776


In [6]:
import tensorflow as tf

x = 2
y = 3
add_op = tf.add(x, y)
mul_op = tf.multiply(x, y)
uesless = tf.multiply(x, add_op)
pow_op = tf.pow(add_op, mul_op)

with tf.Session() as sess:
    z, not_useless = sess.run([pow_op, uesless])
    
    print("z = {}".format(z))
    print("not_uesless = {}".format(not_useless))

z = 15625
not_uesless = 10


In [7]:
# Distributed  Computation

with tf.device('/gpu:0'):
    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], name='a')
    b = tf.constant([6.0, 5.0, 4.0, 3.0, 2.0, 1.0], name='b')
    c = tf.multiply(a, b)
    
    sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
    print(sess.run(c))

[ 6. 10. 12. 12. 10.  6.]


### Graph

In [11]:
# create graph

g = tf.Graph()

with g.as_default():
    x = tf.add(3, 5)
    
sess = tf.Session(graph=g)
print(sess.run(x))

sess.close()

8


In [12]:
# different graphs

g1 = tf.get_default_graph()
g2 = tf.Graph()

# add ops to the default graph
with g1.as_default():
    a = tf.constant(3)
    
# add ops to the user created graph
with g2.as_default():
    b = tf.constant(5)
    
with tf.Session(graph=g1) as sess:
    print(sess.run(a))
    
with tf.Session(graph=g2) as sess1:
    print(sess1.run(b))

3
5


### Operations

In [13]:
import tensorflow as tf 

a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)

with tf.Session() as sess:
    print(sess.run(x))

5


### Tensorboard

In [15]:
import tensorflow as tf

a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)

#writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())

with tf.Session() as sess:
    writer = tf.summary.FileWriter('F:\project\GitHub-Project\keras-learning-API\TF\\tf_tutorial\graphs/graphs', sess.graph)
    print(sess.run(x))
    
writer.close()

"""
tensorboard --logdir='./graphs' --port 6006  # 6006 or any port you want
"""

5


In [16]:
import tensorflow as tf 

a = tf.constant(2, name='a')
b = tf.constant(3, name='b')
x = tf.add(a, b, name='add')

writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())

with tf.Session() as sess:
    print(sess.run(x))

5


### Constant

In [17]:
import tensorflow as tf 

a = tf.constant([2, 2], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')
x = tf.multiply(a, b, name='mul')

with tf.Session() as sess:
    print(sess.run(x))

[[0 2]
 [4 6]]


In [18]:
import tensorflow as tf

a = tf.zeros([2, 3], tf.int32)

with tf.Session() as sess:
    print(sess.run(a))

[[0 0 0]
 [0 0 0]]


In [19]:
import tensorflow as tf 

a_fill = tf.fill([2, 3], 8)

with tf.Session() as sess:
    print(sess.run(a_fill))

[[8 8 8]
 [8 8 8]]


In [20]:
a_lin = tf.lin_space(10.0, 13.0, 4)
a_rg1 = tf.range(3, 18, 3)
a_rg2 = tf.range(5)

with tf.Session() as sess:
    print('a_lin = {}'.format(sess.run(a_lin)))
    print('a_rg1 = {}'.format(sess.run(a_rg1)))
    print('a_rg2 = {}'.format(sess.run(a_rg2)))

a_lin = [10. 11. 12. 13.]
a_rg1 = [ 3  6  9 12 15]
a_rg2 = [0 1 2 3 4]


In [22]:
import tensorflow as tf 

t_0d = 19
a = tf.zeros_like(t_0d)
b = tf.ones_like(t_0d)

with tf.Session() as sess:
    print("zeros_like = {}".format(sess.run(a)))
    print("ones_like = {}".format(sess.run(b)))

zeros_like = 0
ones_like = 1


In [23]:
t_2d = [[True, False, False],
        [False, False, True],
        [False, True, False]]

a = tf.zeros_like(t_2d)
b = tf.ones_like(t_2d)

with tf.Session() as sess:
    print("a = {}".format(sess.run(a)))
    print("b = {}".format(sess.run(b)))

a = [[False False False]
 [False False False]
 [False False False]]
b = [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### print the graph def

In [24]:
my_const = tf.constant([1.0, 2.0], name='my_const')

with tf.Session() as sess:
    print(sess.graph.as_graph_def())

### Init variables

In [ ]:
s = tf.get_variable('scalar', initializer=tf.constant(2))
m = tf.get_variable('matrix', initializer=tf.constant([[0, 1], [2, 3]]))
W = tf.get_variable('big_matrix', shape=(784, 10), initializer=tf.zeros_initializer())

# init all variables
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    
# init a subset of variables
with tf.Session() as sess:
    init_op = tf.variables_initializer([s, m])
    
# init a single variable
with tf.Session() as sess:
    sess.run(W.initializer)

### eval()

In [25]:
W = tf.Variable(tf.truncated_normal([700, 10]))

with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval())

[[ 0.10399167 -0.69239116 -0.08605107 ... -0.745488    0.71715546
  -0.5817648 ]
 [-0.32825926 -0.96562445  0.37092894 ... -1.1366675   1.5661988
   0.5501632 ]
 [ 0.66950953  0.3321359   1.2843357  ... -0.5516824  -0.9335099
   0.1032984 ]
 ...
 [ 0.6123584  -1.755268    0.18156879 ...  0.9707897  -1.5216535
  -0.27090156]
 [-0.6479692   0.12597033 -0.01425168 ...  0.14701861  0.22243348
   0.80876994]
 [-0.3695642   1.1874684   0.27899435 ... -0.10850231 -1.1420717
  -0.5229709 ]]


### assign()

In [26]:
W = tf.Variable(10)
W.assign(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval())
    
W1 = tf.Variable(10)
assign_op = W1.assign(100)
with tf.Session() as sess:
    sess.run(W1.initializer)
    sess.run(assign_op)
    print(W1.eval())

10
100


In [27]:
my_var = tf.Variable(2, name='my_var')

my_var_times_two = my_var.assign(2 * my_var)

with tf.Session() as sess:
    sess.run(my_var.initializer)
    print(sess.run(my_var_times_two))
    print(sess.run(my_var_times_two))
    print(sess.run(my_var_times_two))

4
8
16


### assign_add  assign_sub

In [28]:
my_var = tf.Variable(10)

with tf.Session() as sess:
    sess.run(my_var.initializer)
    
    print(sess.run(my_var.assign_add(10)))
    print(sess.run(my_var.assign_sub(2)))

20
18


### diffrent sessions

In [29]:
W = tf.Variable(10)
sess1 = tf.Session()
sess2 = tf.Session()

sess1.run(W.initializer)
sess2.run(W.initializer)

print(sess1.run(W.assign_add(10)))
print(sess2.run(W.assign_sub(2)))

print(sess1.run(W.assign_add(100)))
print(sess2.run(W.assign_sub(50)))

sess1.close()
sess2.close()

20
8
120
-42


### Placeholder

In [30]:
a = tf.placeholder(tf.float32, shape=[3])
b = tf.constant([5, 5, 5], tf.float32)
c = a + b

with tf.Session() as sess:
    print(sess.run(c, {a:[1, 2, 3]}))

[6. 7. 8.]


In [31]:
a = tf.add(2, 5)
b = tf.multiply(a, 3)

with tf.Session() as sess:
    b = sess.run(b, feed_dict={a: 15})
    print('b = {}'.format(b))

b = 45


### lazy load

In [32]:
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')

writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for _ in range(10):
        sess.run(tf.add(x, y))
        
    writer.close()

### tf.variable_scope()

In [ ]:
def two_hidden_layer(x):
    assert x.shape.as_list() == [200, 100]
    w1 = tf.get_variable('h1_weights', [100, 50], initializer=tf.random_normal_initializer())
    b1 = tf.get_variable('h1_biases', [50], initializer=tf.constant_initializer(0.0))
    h1 = tf.matmul(x, w1) + b1
    
    assert h1.shape.as_list() == [200, 50]
    w2 = tf.get_variable('h2_weights', [50, 10], initializer=tf.random_normal_initializer())
    b2 = tf.get_variable('h2_biases', [10], initializer=tf.constant_initializer(0.0))
    logits = tf.matmul(h1, w2) + b2
    
    return logits

with tf.variable_scope('two_layers') as scope:
    logits1 = two_hidden_layer(x1)
    scope.reuse_variables()
    logits2 = two_hidden_layer(x2)
    

In [ ]:
def fully_connected(x, output_dim, scope):
    with tf.variable_scope(scope, reuse=tf.AUTO_REUSE) as scope:
        w = tf.get_variable('weights', [x.shape[1], output_dim], initializer=tf.random_normal_initializer())
        b = tf.get_variable('biases', [output_dim], initializer=tf.constant_initializer(0.0))
        
def two_hidden_layers(x):
    h1 = fully_connected(x, 50, 'h1')
    h2 = fully_connected(h1, 10, 'h2')
    
with tf.variable_scope('two_layers') as scope:
    logits1 = two_hidden_layer(x1)
    logits2 = two_hidden_layer(x2)

### Train Save Restore

In [ ]:
# Save

# define model
model = ...
saver = tf.train.Saver()

with tf.Session() as sess:
    for step in range(training_steps):
        sess.run([optimizer])
        
        if (step + 1) % 1000 == 0:
            saver.save(sess, 'checkpoint_dir/model_name', global_step=step)

In [ ]:
# global step
global_step = tf.Variable(0, dtype=tf.int32, trainable=False, name='global_step')
optimizer = tf.train.AdamOptimizer(lr).minimize(loss, global_step=global_step)

In [ ]:
# save certain variables

v1 = tf.Variable(..., name='v1')
v2 = tf.Variable(..., name='v2')

saver = tf.train.Saver({'v1':v1, 'v2':v2})

saver = tf.train.Saver({v1, v2})

saver = tf.train.Saver({v.op.name: v for v in [v1, v2]})

In [ ]:
# restore

saver.restore(sess, 'checkpoints/name_of_the_checkpoint')

ckpt = tf.train.get_checkpoint_state(os.path.dirname('checkpoints/checkpoint'))
if ckpt and ckpt.model_checkpoint_path:
    saver.restore(sess, ckpt.model_checkpoint_path)

### tf.summary()

In [ ]:
with tf.name_scope('summary'):
    tf.summary.scalar('loss', self.loss)
    tf.summary.scalar('accuracy', self.accuracy)
    tf.summary.histogram('histogram loss', self.loss)
    summary_op = tf.summary.merge_all()
    
    saver = tf.train.Saver()
    
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        ckpt = tf.train.get_checkpoint_state(os.path.dirname('checkpoints/checkpiont'))
        if ckpt and ckpt.model_checkpoint_path:
            saver.restore(sess, ckpt.model_checkpoint_path)
            
        writer = tf.summary.FileWriter('./graphs', sess.graph)
        
        for index in range(100000):
            ...
            loss_batch, _, summary = sess.run([loss, optimizer, summary_op])
            writer.add_summary(summary, global_step=step)
            
            if (index + 1) % 1000 == 0:
                saver.save(sess, 'checkpoints/model_name', index)